Userinterface overzicht rondleidingen voor bezoeker
Kevin4032/ProjectB pull request #13
Opened 2023-03-08 16:23 UTC by rhlt

Ik heb het geprobeerd niet te ingewikkeld te maken. Alles zit binnen één class (TourList.cs), maar dat mag later denk ik nog wel wat meer abstracted worden voor verschillende soorten schermen binnen de interface.

2023-03-10 13:15 UTC, TomBaakHR requested changes
Ziet er goed uit en werkt soepel. Wellicht afvangen dat invoerde keys die geen functie hebben niet in de console geschreven worden.

2023-03-10 20:06 UTC, rhlt commented
@TomBaakHR, ik heb het tonen van de keys in de console opgelost. Daarnaast heb ik simpele pagination toegevoegd voor als de lijst van tijden niet in één keer of het scherm past (eerst kwamen er dan rare dingen).

2023-03-12 11:47 UTC, Kevin4032 approved these changes
Ziet er goed uit, prima eerste versie en goede voorstellen om later uit te werken.

2023-03-12 13:47 UTC, TomBaakHR approved these changes

2023-03-12 13:49 UTC, TomBaakHR commented
Netjes die pagination!

2023-03-12 13:49 UTC, merged