Enter code
Kevin4032/ProjectB pull request #16
Opened 2023-03-13 09:27 UTC by KarlijnJ

2023-03-13 10:10 UTC, rhlt requested changes
Een goed begin. Ik zie dat je een deel weggecomment hebt. Lukte het allemaal wel een beetje?

Toch een paar puntjes:

- Zou je je code in een eigen class willen zetten? Dus niet in Program.cs, maar bijvoorbeeld EnterCode.cs? Als iedereen alles in Progam.cs zet, vindt Git dat niet zo leuk.
- Ik denk niet dat we ervan uit mogen gaan dat codes altijd een nummer zijn. Ook hoef je niet met toegangscodes te rekenen (code1 + code2 = ... code 3?). Misschien kan je er beter een string van maken in plaats van een int.

2023-03-13 12:33 UTC, Kevin4032 commented
In ons document staat als requirement, al is de vraag of de docent zich hier aan houdt;
o	Entreebewijs.
	Begint met E, gevolgd door 10 cijfers.
•	E##########
o	Personeelnummer.
	Begint met D, gevolgd door 10 cijfers.
•	D##########

2023-03-13 12:51 UTC, rhlt commented
@Kevin4032, je hebt gelijkt maar volgens mij is validatie de verantwoordelijkheid van de models (dat heb jij toch al gemaakt?), dus daar hoeft de Enter Code function eigenlijk geen rekening mee te houden. Behalve misschien jouw models aanroepen natuurlijk.

2023-03-13 12:55 UTC, Kevin4032 commented
Je hebt gelijk @rhlt

2023-03-13 19:01 UTC, TomBaakHR requested changes
Zou je een functionaliteit kunnen toevoegen die check of er daadwerklijk iets word ingevoerd?

2023-03-15 15:28 UTC, rhlt commented
Deze code heb ik verwerkt in pull request #21 (KarlijnsTestController.cs).

2023-03-15 15:28 UTC, closed without merging