Create a system that can easily render things to the console
Kevin4032/ProjectB pull request #22
Opened 2023-03-15 21:41 UTC by TomBaakHR

Mijn opzet voor de Views. In Program.cs heb ik comments met uitleg geschreven.

2023-03-16 12:00 UTC, rhlt requested changes
Er is nu een conflict op Program.cs omdat ik al onze testdata naar testcontrollers had verplaatst. Kan je dat hier ook doen, dus wat nu op Develop staat mergen en je nieuwe gegevens van Program.cs verplaatsen naar TomsTestController.cs?

2023-03-16 19:56 UTC, rhlt commented
Het is een mooi, flexibel systeem. Hier kunnen we zeker mee verder. Een paar dingetjes die ik nog tegenkom:

- Er gaat nog ergens iets mis bij de Ja/Nee list view ("Er is al een reservering voor vandaag"), het geselecteerde item licht maar half op;
- In ListView.cs heb je een paar warnings over mogelijke Nullable types. Kan je daar in de code rekening mee houden dat sommige variabeles null kunnen zijn? Dat is wel zo netjes;
- Sommige classes als ListViewItem en ListViewPartedItem hebben wel erg veel constructors. Veel kan je er samenvoegen door default values te gebruiken. In plaats van 3 verschillende constructors heb je dan genoeg aan één:
 `public ListViewItem(string text, object value, bool disabled = false, int textAlignment = 0) : base(value, disabled, textAlignment) => Text = text;`

2023-03-17 17:06 UTC, rhlt approved these changes
Ziet er mooi uit, ik heb er een paar kleine opmerkingen tussen gezet maar dat is allemaal niet zo belangrijk.

2023-03-17 17:06 UTC, rhlt commented on HetDepot/Controllers/Tests/RubensTestController.cs
Blijkbaar is "mijn" testcontroller verdwenen

2023-03-17 17:06 UTC, rhlt commented on HetDepot/Controllers/Tests/TestController.cs
> -            "ruben" => new RubensTestController(),
Is hier een reden voor?

2023-03-17 17:06 UTC, rhlt commented on HetDepot/Views/AlertView.cs
> +        Thread.Sleep(SleepTime);
Ik vind Sleep eigenlijk geen mooie oplossing. Liever iets als "druk op een toets", en als je dat niet doet na een paar seconden automatisch door. Maar dat is wel wat ingewikkelder, dus voor nu is het wel goed.

2023-03-17 18:07 UTC, Kevin4032 approved these changes

2023-03-17 18:07 UTC, merged