Enter code + Enter Visitor
Kevin4032/ProjectB pull request #29
Opened 2023-03-27 13:48 UTC by KarlijnJ

Ik heb een nieuwe class aangemaakt voor het invoeren van de code door de gids. 
Ik zit nog een beetje te stoeien met hoe om te gaan als er een verkeerd format code wordt ingevoerd. 
Ik heb het als commentaar erbij gezet maar ik hoor graag jullie input.

2023-03-27 13:53 UTC, rhlt commented
Je hebt wel een Merge conflict. Is je branch misschien gebaseerd op een hele oude state van Develop?
Je kan eventueel in VScode ook de huidige Develop branch naar deze branch mergen, dan kan je het op je eigen PC nog testen.

2023-03-27 14:01 UTC, Kevin4032 requested changes
Goed begin, het kan iets verder uitgediept worden.

2023-03-27 14:01 UTC, Kevin4032 commented on HetDepot/Program.cs
> +EnterCode.AskforCode();
Dit is niet heel DRY https://en.wikipedia.org/wiki/Don%27t_repeat_yourself
Ook sluit ik mij aan bij Ruben, kijk of je kunt aansluiten op een controle, en ook verificatie kunt doen.

2023-04-17 17:03 UTC, TomBaakHR commented
Karlijn heeft ons verlaten

2023-04-17 17:03 UTC, closed without merging