Feat/statistic overview
Kevin4032/ProjectB pull request #37
Opened 2023-05-08 13:49 UTC by TomBaakHR

2023-05-08 13:50 UTC, rhlt commented
Dat zijn een hoop conflicts. Misschien eerste de nieuwste develop hierin mergen?

2023-05-08 17:58 UTC, Kevin4032 requested changes
Zie comments

2023-05-08 17:58 UTC, Kevin4032 commented on HetDepot/Settings/SettingService.cs
> +            var tours = tourTimes.Select((string time) =>
In het eerdere ontwerp werden de tours pas geschrevne als de eerste reserering is gedaan.

Daarnaast, ik zou de settings niet de tours laten schrijven, dan zou ik de toursservice zelf de tours laten schrijven. (en dus in de tourserivce het pad laten ophalnen uit de settingservice)

2023-05-08 17:58 UTC, Kevin4032 commented on HetDepot/Settings/SettingService.cs
> +            writer.Close();
Dit laten lopen via repository. Als je in de tourservice dat doet met een write komt dat goed.
Regel 115(
        private void WriteTourData()
        {
            _repository.Write(_tours);
        })

2023-05-08 17:58 UTC, Kevin4032 commented on HetDepot/Settings/SettingService.cs
> +            return $"{TourFilePrefix}{today.Day}_{today.Month}_{today.Year}.json";
tourfileprefix_yyyyMMdd of,aan gezien we een nieuwe folder 'workinfilfes' hebben, noem de folder 'tours' of 'tourdadta' en schrijf files met de datum van vandaag.
bv. \Tourdata\20230508.json

2023-05-08 17:58 UTC, Kevin4032 commented on HetDepot/Tours/Model/Tour.cs
> -            Guide = guide;
Waarom is de gids eruit?

2023-05-08 17:58 UTC, Kevin4032 commented on HetDepot/Controllers/General/ManagerController.cs
> +        if (true) // TODO Check if personnelCode is valid
if personnelCode == PeopleService.GetManager().Id

Allicht van personnelcode naar employeecode.

2023-05-08 17:58 UTC, Kevin4032 commented on HetDepot/HetDepot.csproj
> +<!--    <None Update="ExampleFile\ExampleTours.json">-->
Ik zou hem op never zetten, de eerste keer wordt aangemaakt obv de settingsfile
Dus, aan het begin van de dag, eerste keer opstasrte n= uitlezen uit settingsfile.
Bij de eerste reservering, schrijven.

Daarnaast, die gaat nog over 'examplefile\exampletours\, volgens mim heb je dat ook aangepast.

2023-05-08 18:19 UTC, TomBaakHR commented on HetDepot/Tours/Model/Tour.cs
> -            Guide = guide;
Daarom

2023-05-15 13:16 UTC, rhlt approved these changes
Ziet er mooi uit. Je hebt alleen nog niet de nieuwste ListView (die nodig wat voor het gids gedeelte), dus ik ga ondertussen kijken of ik deze gemerged krijg in merge-all.

2023-05-15 13:37 UTC, rhlt commented
@TomBaakHR: Ik heb dit ook gemerged naar de merge-all branch (#42), maar omdat daarin een nieuwere ListView zit kostte dat best wel een paar wijzigingen. Kan je daarom de merge-all bij jou binnenhalen en testen of alles dat hieruit komt, daarin ook goed werkt?

Als je hierin nog wijzigingen doet, zou je dan eerst merge-all naar jouw branch toe willen mergen?
Ik zie trouwens nog wel een dingetje: Het lijkt erop dat iedere inlogcode van het afdelingshoofd geaccepteerd wordt. Is dat de bedoeling?

2023-05-15 13:42 UTC, Kevin4032 approved these changes

2023-05-15 13:42 UTC, merged