Gids starten rol
Kevin4032/ProjectB pull request #38
Opened 2023-05-08 14:19 UTC by Ted-Ru

Gids stapsgewijs aanmelden bezoekers met controle code op vadiliteit.
Starten rondleiding.
Gids controle eigen inlogcode.
Niet helemaal klaar: console beep ontbreekt nog, en handmatig aanmelden bezoekercode zonder reservering.

2023-05-08 14:56 UTC, Kevin4032 requested changes
Zie comments

2023-05-08 14:56 UTC, Kevin4032 commented on HetDepot/Controllers/StaffInvalidLoginController.cs
> +class StaffInvalidLoginController : Controller
Employee ipv staff

2023-05-08 14:56 UTC, Kevin4032 commented on HetDepot/Controllers/General/GuideController.cs
> +        if (isGuide) // TODO Check if personnelCode is valid
Todo kan weg, dat is op regel 28

2023-05-08 14:56 UTC, Kevin4032 commented on HetDepot/Controllers/General/GuideController.cs
> +        else if (isGuide == false)
if (isGuide == false) kan weg, dat is wat 'false' signaleert

2023-05-08 14:56 UTC, Kevin4032 commented on HetDepot/Controllers/GuideShowAndSelectTourController.cs
> +            ListView<Tour> tourOverviewVisitorWithInterface = new(Program.SettingService.GetConsoleText("consoleGuideTourShowToursToStart"), tourList);
Zorgen dat je geen rondleiding met 0 bezoekers kunt selecteren; ik heb de huidige branch lokaal gehaald, er staat netjes 0 resrverigen, maar ik kan wel 'enteren' en aanmelden.

2023-05-08 14:56 UTC, Kevin4032 commented on HetDepot/Controllers/GuideStartTourAdmissionController.cs
> +        if (Program.TourService.HasReservation(new Visitor(personIDToVerify)))
Geen nieuwe ID aanmaken.

2023-05-08 14:56 UTC, Kevin4032 commented on HetDepot/Controllers/GuideStartTourAdmissionController.cs
> +            _tour.AddAdmission(new Visitor(personIDToVerify));
Geen nieuwe ID aanmaken

2023-05-08 14:56 UTC, Kevin4032 commented on HetDepot/Controllers/GuideStartTourAdmissionController.cs
> +            var message = $"De code {personIDToVerify} heeft geen reservering.";
Dito

2023-05-08 14:56 UTC, Kevin4032 commented on HetDepot/Controllers/GuideStartTourAdmissionController.cs
> +        var personIDToVerify = new InputView($"{_tour.Admissions.Count()} bezoekers hebben zich aangemeld.", " Voer jouw unieke code in, of typ \"start\" om de rondleiding te starten zonder anderen a
Deze personIDToverify aanhouden tegen _peopleService.
Het visitor object dat je terugkrijgt verderop gebruiken

2023-05-08 14:56 UTC, Kevin4032 commented on HetDepot/Tours/Model/Tour.cs
> +                disabled
Deze disabled kan gebruikt worden op de andere plek waar rondleidng met 0 reserverigen aangemeld moeten.

2023-05-08 15:01 UTC, rhlt commented on HetDepot/Controllers/GuideShowAndSelectTourController.cs
> +            ListView<Tour> tourOverviewVisitorWithInterface = new(Program.SettingService.GetConsoleText("consoleGuideTourShowToursToStart"), tourList);
Daar ben ik het niet mee eens. Handmatig aanmelden moet er namelijk nog aan toegevoegd worden, en waarom zou je niet mogen starten met alleen handmatige aanmeldingen?

2023-05-08 15:02 UTC, rhlt commented on HetDepot/Tours/Model/Tour.cs
> +                disabled
Dat is mijn code; heb ik bewust niet gedaan vanwege handmatig aanmelden

2023-05-09 08:37 UTC, Kevin4032 requested changes
Files verplaatsen.

2023-05-09 08:37 UTC, Kevin4032 commented on HetDepot/Controllers/GuideShowAndSelectTourController.cs
Graag deze file ook onder /controllers/guide

2023-05-09 08:37 UTC, Kevin4032 commented on HetDepot/Controllers/GuideStartTourAdmissionController.cs
Ook deze file graag onder /controllers/guide

2023-05-09 08:37 UTC, Kevin4032 commented on HetDepot/Controllers/StaffInvalidLoginController.cs
Als deze file alleen voor gids is, graag onder /controllers/guide.

2023-05-09 08:37 UTC, Kevin4032 requested changes
Files verplaatsen.

2023-05-09 08:45 UTC, Kevin4032 requested changes

2023-05-09 08:45 UTC, Kevin4032 commented on HetDepot/Controllers/General/GuideController.cs
Deze file mag ook naar /controllers/guide

2023-05-12 12:08 UTC, Ted-Ru commented
alle gevraagde aanpassingen zijn doorgevoerd.

2023-05-12 12:11 UTC, rhlt commented
@Ted-Ru, waar heb je de aanpassingen precies doorgevoerd? Op een andere branch? Ik zie geen commits op deze branch, en je hebt de pull gesloten, wat normaal betekent dat je geen pull meer wilt doen vanaf deze branch.

2023-05-12 12:46 UTC, Ted-Ru commented
Excuus, nu heb ik de veranderingen als het goed is wel gecommit.
________________________________
From: Ruben Holthuijsen ***@***.***>
Sent: Friday, May 12, 2023 12:11 PM
To: Kevin4032/TheChamps ***@***.***>
Cc: Ted-Ru ***@***.***>; Mention ***@***.***>
Subject: Re: [Kevin4032/TheChamps] Gids starten rol (PR #38)


@Ted-Ru<https://github.com/Ted-Ru>, waar heb je de aanpassingen precies doorgevoerd? Op een andere branch? Ik zie geen commits op deze branch, en je hebt de pull gesloten, wat normaal betekent dat je geen pull meer wilt doen vanaf deze branch.

—
Reply to this email directly, view it on GitHub<https://github.com/Kevin4032/TheChamps/pull/38#issuecomment-1545647139>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AU7VJOX72OVDAQQUXAROLPLXFYSIXANCNFSM6AAAAAAX2AMYUE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-05-12 14:45 UTC, Kevin4032 submitted a review, later dismissed

2023-05-12 15:57 UTC, rhlt commented
De laatste commit die hier in zit is van 8 mei, kan dat kloppen?

2023-05-12 15:58 UTC, rhlt approved these changes, later dismissed

2023-05-15 13:25 UTC, rhlt approved these changes, later dismissed
Ik heb de nieuwste develop hierin gemerged en daarmee een conflict gefixt (graag zelf even een pull doen!)

2023-05-15 13:45 UTC, Kevin4032 submitted a review, later dismissed

2023-05-15 13:53 UTC, rhlt commented
Staat nu in merge-all

2023-05-15 13:53 UTC, closed without merging