Alles in 1x mergen
Kevin4032/ProjectB pull request #42
Opened 2023-05-14 12:51 UTC by rhlt

2023-05-14 19:34 UTC, TomBaakHR requested changes

2023-05-14 19:34 UTC, TomBaakHR commented on HetDepot/Controllers/Guide/GuideNoReservationsForThisTourController.cs
Deze implementatie leidt tot een gekke flow. Ik zou deze aanpassen naar een AlertView die daarna automatisch terug gaat naar het gids tour overzicht.

2023-05-14 19:34 UTC, TomBaakHR commented on HetDepot/Controllers/Guide/GuideReservationCreateController.cs
Hier moet de NextController veranderd worden om te zorgen dat er weer naar de GuideStartTourAdmissionController gegaan wordt

2023-05-15 08:44 UTC, rhlt commented on HetDepot/Controllers/Guide/GuideNoReservationsForThisTourController.cs
Het is iets ingewikkelder, want een gids moet ook nog mensen handmatig aan kunnen melden. Waarom zou dat niet kunnen als er geen reserveringen zijn?

Daar moet nog naar gekeken worden, maar dat lijkt me te veel om vandaag nog even te doen dus ik zet deze op "resolved". Help ons maar herinneren!

2023-05-15 08:47 UTC, rhlt commented on HetDepot/Controllers/Guide/GuideReservationCreateController.cs
Gefixt

2023-05-15 14:45 UTC, Ted-Ru approved these changes, later dismissed

2023-05-22 16:41 UTC, TomBaakHR approved these changes

2023-05-22 16:42 UTC, Kevin4032 approved these changes
Klasse

2023-05-22 16:42 UTC, merged